export enum ErrorTypes {
    MISSING_ID = "MISSING_ID",
    INVALID_ID = "INVALID_ID",
    NOT_FOUND = "NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    SERVER_ERROR = "SERVER_ERROR",
    APPLICATION_ERROR = "APPLICATION_ERROR",
  }
  